# Generated by Django 6.0.3 on 2026-04-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_login_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginevent',
            name='client_city',
            field=models.CharField(blank=True, help_text='City from GeoIP when configured.', max_length=128),
        ),
        migrations.AddField(
            model_name='loginevent',
            name='client_country',
            field=models.CharField(blank=True, help_text='ISO country code or name from GeoIP when configured.', max_length=64),
        ),
    ]
