from django.urls import path

from .views import (
    ShellUIAdminGroupDetailView,
    ShellUIAdminGroupListView,
    ShellUIAdminLoginEventDetailView,
    ShellUIAdminLoginEventListView,
    ShellUIAdminLoginRedirectDetailView,
    ShellUIAdminLoginRedirectListView,
    ShellUIAdminGlobalMetricsView,
    ShellUIAdminMetricsView,
    ShellUIAdminUserDetailView,
    ShellUIAdminUserListView,
    ShellUIAuthSettingsView,
    ShellUIAuthorizeView,
    ShellUILogoutView,
    ShellUIOAuthCallbackView,
    ShellUIPreferenceView,
    ShellUITokenView,
    ShellUIUserView,
    SocialAuthorizeView,
    SocialLoginView,
)

urlpatterns = [
    path('settings', ShellUIAuthSettingsView.as_view(), name='shellui-settings'),
    path('authorize', ShellUIAuthorizeView.as_view(), name='shellui-authorize'),
    path('oauth/callback', ShellUIOAuthCallbackView.as_view(), name='shellui-oauth-callback'),
    path('token', ShellUITokenView.as_view(), name='shellui-token'),
    path('logout', ShellUILogoutView.as_view(), name='shellui-logout'),
    path('user', ShellUIUserView.as_view(), name='shellui-user'),
    path('admin/groups', ShellUIAdminGroupListView.as_view(), name='shellui-admin-groups'),
    path('admin/groups/<int:pk>', ShellUIAdminGroupDetailView.as_view(), name='shellui-admin-group-detail'),
    path('admin/login-redirects', ShellUIAdminLoginRedirectListView.as_view(), name='shellui-admin-login-redirects'),
    path(
        'admin/login-redirects/<int:pk>',
        ShellUIAdminLoginRedirectDetailView.as_view(),
        name='shellui-admin-login-redirect-detail',
    ),
    path('admin/users', ShellUIAdminUserListView.as_view(), name='shellui-admin-users'),
    path('admin/login-events', ShellUIAdminLoginEventListView.as_view(), name='shellui-admin-login-events'),
    path('admin/login-events/<int:pk>', ShellUIAdminLoginEventDetailView.as_view(), name='shellui-admin-login-event-detail'),
    path('admin/metrics', ShellUIAdminMetricsView.as_view(), name='shellui-admin-metrics'),
    path('admin/metrics/all', ShellUIAdminGlobalMetricsView.as_view(), name='shellui-admin-metrics-all'),
    path('admin/users/<int:pk>', ShellUIAdminUserDetailView.as_view(), name='shellui-admin-user-detail'),
    path('preferences', ShellUIPreferenceView.as_view(), name='shellui-preferences'),
    path('providers/<str:provider>/authorize/', SocialAuthorizeView.as_view(), name='social-authorize'),
    path('providers/<str:provider>/login/', SocialLoginView.as_view(), name='social-login'),
]
