# Generated by Django 6.0.3 on 2026-04-06 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], db_index=True, max_length=16)),
                ('provider', models.CharField(db_index=True, max_length=32)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('is_staff_at_event', models.BooleanField(db_index=True, default=False)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('client_timezone', models.CharField(blank=True, max_length=64)),
                ('client_device_id_hash', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='authapi_log_user_id_07022b_idx')],
            },
        ),
    ]
